package model.verbs;

public enum CuttingVerbWordVerbNet implements ISearchableVerb {
    // "Cut" and its different hyponyms taken from Thesaurus, VerbNet and WordNet.
    // We only include verbs relevant for the cooking domain.
    // The past and participle forms are taken from https://en.pons.com/verb-tables/english
    ABBREVIATE("abbreviate", "abbreviated", "abbreviating"),
    ABRIDGE("abridge", "abridged", "abridging"),
    BARK("bark", "barked", "barking"),
    BEVEL("bevel", "bevelled", "bevelling"),
    BISECT("bisect", "bisected", "bisecting"),
    BITE("bite", "bit", "biting"),
    BLAST("blast", "blasted", "blasting"),
    BLOW("blow", "blew", "blowing"),
    BOB("bob", "bobbed", "bobbing"),
    BORE("bore", "bored", "boring"),
    BOWDLERISE("bowdlerise", "bowdlerised", "bowdlerising"),
    BOWDLERIZE("bowdlerize", "bowdlerized", "bowdlerizing"),
    BRAID("braid", "braided", "braiding"),
    BREAK("break", "broke", "breaking"),
    BRING("bring", "brought", "bringing"),
    BRUISE("bruise", "bruised", "bruising"),
    BRUSH("brush", "brushed", "brushing"),
    BUILT("build", "built", "building"),
    BUMP("bump", "bumped", "bumping"),
    BUNK("bunk", "bunked", "bunking"),
    BURN("burn", "burned", "burning"),
    CARVE("carve", "carved", "carving"),
    CASTRATE("castrate", "castrated", "castrating"),
    CHAMFER("chamfer", "chamfered", "chamfering"),
    CHASE("chase", "chased", "chasing"),
    CHATTER("chatter", "chattered", "chattering"),
    CHECK("check", "checked", "checking"),
    CHIP("chip", "chipped", "chipping"),
    CHOP("chop", "chopped", "chopping"),
    CIRCUMCISE("circumcise", "circumcised", "circumcising"),
    CLIP("clip", "clipped", "clipping"),
    COLDCREAM("coldcream", "coldcreamed", "coldcreaming"),
    COMB("comb", "combed", "combing"),
    CONCENTRATE("concentrate", "concentrated", "concentrating"),
    CONDENSE("condense", "condensed", "condensing"),
    CONDITION("condition", "conditioned", "conditioning"),
    CONTRACT("contract", "contracted", "contracting"),
    CRADLE("cradle", "cradled", "cradling"),
    CRIMP("crimp", "crimped", "crimping"),
    CROP("crop", "cropped", "cropping"),
    CROSSCUT("crosscut", "crosscut", "crosscutting"),
    CUBE("cube", "cubed", "cubing"),
    CURL("curl", "curled", "curling"),
    CURVE("curve", "curved", "curving"),
    CUT("cut", "cut", "cutting"),
    DEFLATE("deflate", "deflated", "deflating"),
    DETRACT("detract", "detracted", "detracting"),
    DICE("dice", "diced", "dicing"),
    DIGEST("digest", "digested", "digesting"),
    DILUTE("dilute", "diluted", "diluting"),
    DISCERP("discerp", "discerped", "discerping"),
    DISREGARD("disregard", "disregarded", "disregarding"),
    DISSECT("dissect", "dissected", "dissecting"),
    DOCK("dock", "docked", "docking"),
    DOWNSIZE("downsize", "downsized", "downsizing"),
    DRAW("draw", "drew", "drawing"),
    DRILL("drill", "drilled", "drilling"),
    DROP("drop", "dropped", "dropping"),
    DYE("dye", "dyed", "dyeing"),
    EDIT("edit", "edited", "editing"),
    EXPURGATE("expurgate", "expurgated", "expurgating"),
    FELL("fell", "felled", "felling"),
    FILE("file", "filed", "filing"),
    FORESHORTEN("foreshorten", "foreshortened", "foreshortening"),
    FRENCH("French", "French", "French"),
    FURROW("furrow", "furrowed", "furrowing"),
    GASH("gash", "gashed", "gashing"),
    GELD("geld", "gelded", "gelding"),
    GORE("gore", "gored", "goring"),
    HACK("hack", "hacked", "hacking"),
    HENNA("henna", "hennaed", "hennaing"),
    HEW("hew", "hewed", "hewing"),
    HOB("hob", "hobbed", "hobbing"),
    HURT("hurt", "hurt", "hurting"),
    IGNORE("ignore", "ignored", "ignoring"),
    INCISE("incise", "incise", "incising"),
    INDENT("indent", "indented", "indenting"),
    INFLATE("inflate", "inflated", "inflating"),
    INJURE("injure", "injured", "injuring"),
    ISSUE("issue", "issued", "issuing"),
    JAG("jag", "jag", "jagging"),
    JULIENNE("julienne", "julienned", "julienning"),
    KICK("kick", "kicked", "kicking"),
    KILL("kill", "killed", "killing"),
    KNAP("knap", "knapped", "knapping"),
    KNOCK("knock", "knocked", "knocking"),
    LATHER("lather", "lathered", "lathering"),
    LOP("lop", "lopped", "lopping"),
    MAKE("make", "made", "making"),
    MANICURE("manicure", "manicured", "manicuring"),
    MORTICE("mortice", "morticed", "morticing"),
    MORTISE("mortise", "mortised", "mortising"),
    MOW("mow", "mowed", "mowing"),
    NICK("nick", "nicked", "nicking"),
    NIP("nip", "nipped", "nipping"),
    PARE("pare", "pared", "paring"),
    PART("part", "parted", "parting"),
    PEEL("peel", "peeled", "peeling"),
    PERM("perm", "permed", "perming"),
    PINK("pink", "pinked", "pinking"),
    PLAIT("plait", "plaited", "plaiting"),
    PLANE("plane", "planed", "planing"),
    PLAY("play", "played", "playing"),
    PLUCK("pluck", "plucked", "plucking"),
    POWDER("powder", "powdered", "powdering"),
    PRICK("prick", "pricked", "pricking"),
    PRUNE("prune", "pruned", "pruning"),
    PRY("pry", "pried", "prying"),
    PULL("pull", "pulled", "pulling"),
    PUSH("push", "pushed", "pushing"),
    QUENCH("quench", "quenched", "quenching"),
    RATIONALISE("rationalise", "rationalised", "rationalising"),
    RATIONALIZE("rationalize", "rationalized", "rationalizing"),
    REBATE("rebate", "rebated", "rebating"),
    REDUCE("reduce", "reduced", "reducing"),
    RETRENCH("retrench", "retrenched", "retrenching"),
    RINSE("rinse", "rinsed", "rinsing"),
    RIP("rip", "ripped", "ripping"),
    ROLL("roll", "rolled", "rolling"),
    ROUGE("rouge", "rouged", "rouging"),
    SABER("saber", "sabered", "sabering"),
    SABRE("sabre", "sabred", "sabring"),
    SAW("saw", "sawed", "sawing"),
    SCALD("scald", "scalded", "scalding"),
    SCISSOR("scissor", "scissored", "scissoring"),
    SCRAPE("scrape", "scraped", "scraping"),
    SCRATCH("scratch", "scratched", "scratching"),
    SCULPT("sculpt", "sculpted", "sculpting"),
    SET("set", "set", "setting"),
    SEVER("sever", "severed", "severing"),
    SHAMPOO("shampoo", "shampooed", "shampooing"),
    SHAPE("shape", "shaped", "shaping"),
    SHAVE("shave", "shaved", "shaving"),
    SHEAR("shear", "shore", "shearing"),
    SHEER("sheer", "sheered", "sheering"),
    SHORTEN("shorten", "shortened", "shortening"),
    SHOVE("shove", "shoved", "shoving"),
    SKIN("skin", "skinned", "skinning"),
    SKIP("skip", "skipped", "skipping"),
    SLASH("slash", "slashed", "slashing"),
    SLEW("slew", "slewed", "slewing"),
    SLICE("slice", "sliced", "slicing"),
    SLIP("slip", "slipped", "slipping"),
    SLIT("slit", "slit", "slitting"),
    SLUE("slue", "slued", "slueing"),
    SNICK("snick", "snicked", "snicking"),
    SNIP("snip", "snipped", "snipping"),
    SNUB("snub", "snubbed", "snubbing"),
    SOAP("soap", "soaped", "soaping"),
    SPILL("spill", "spilled", "spilling"),
    SPLIT("split", "split", "splitting"),
    STRAIN("strain", "strained", "straining"),
    STRIKE("strike", "struck", "striking"),
    SUBTRACT("subtract", "subtracted", "subtracting"),
    SWERVE("swerve", "swerved", "swerving"),
    SWITCH("switch", "switched", "switching"),
    TAIL("tail", "tailed", "tailing"),
    TAILOR("tailor", "tailored", "tailoring"),
    TAKE("take", "took", "taking"),
    TALC("talc", "talced", "talcing"),
    TAP("tap", "tapped", "tapping"),
    TEAR("tear", "teared", "tearing"),
    TEASE("tease", "teased", "teasing"),
    THIN("thin", "thinned", "thinning"),
    TOMAHAWK("tomahawk", "tomahawked", "tomahawking"),
    TOWEL("towel", "toweled", "toweling"),
    TRANSECT("transect", "transected", "transecting"),
    TRENCH("trench", "trenched", "trenching"),
    TREND("trend", "trended", "trending"),
    TRIM("trim", "trimmed", "trimming"),
    TRISECT("trisect", "trisected", "trisecting"),
    TUG("tug", "tugged", "tugging"),
    TURN("turn", "turned", "turning"),
    UNDERCUT("undercut", "undercut", "undercut"),
    VEER("veer", "veered", "veering"),
    WATER("water", "watered", "watering"),
    WAVE("wave", "waved", "waving"),
    WHITTLE("whittle", "whittled", "whittling"),
    WRITE("write", "wrote", "writing"),
    YANK("yank", "yanked", "yanking"),
    YAW("yaw", "yawed", "yawing");

    private final String present;

    private final String past;

    private final String participle;

    CuttingVerbWordVerbNet(String verb, String past, String participle) {
        this.present = verb;
        this.past = past;
        this.participle = participle;
    }

    @Override
    public boolean doesPresentEqualPast() {
        return present.equals(past);
    }

    @Override
    public String getPresentForm() {
        return present;
    }

    @Override
    public String getPastForm() {
        return past;
    }

    @Override
    public String getParticipleForm() {
        return participle;
    }
}